In [4]:
#This code block is used to load in the datasets from the Github Repo.

import pandas as pd
import numpy as np

url_one = "https://raw.githubusercontent.com/DavidfishMC/CSI4900-Honor-Project/refs/heads/main/phishing_email_detection_dataset_v2.csv"
url_two = "https://raw.githubusercontent.com/DavidfishMC/CSI4900-Honor-Project/refs/heads/main/email_dataset_100k.csv"

df_one = pd.read_csv(url_one) #Read the first csv file given the URL.
df_two = pd.read_csv(url_two) #Read the second csv file given the URL.


print("First basic dataset properties:")
print("Shape:")
print(df_one.shape)

print("\nFirst 5 Rows:")
display(df_one.head())

print("\nInital Data Types:")
print(df_one.dtypes)

print("\nNumber of Distinct Values per Column:")
print(df_one.nunique())

print()
print("Second basic dataset properties:")
print("Shape:")
print(df_two.shape)

print("\nFirst 5 Rows:")
display(df_two.head())

print("\nInital Data Types:")
print(df_two.dtypes)

print("\nNumber of Distinct Values per Column:")
print(df_two.nunique())

First basic dataset properties:
Shape:
(50000, 44)

First 5 Rows:

,email_id,sender_name,sender_email,sender_ip,sender_country,sender_domain,domain_age_days,recipient_email,subject,email_body,...,sent_time,day_of_week,month,hour,language,email_category,device_type,email_client,phishing_probability,label
0,5e691d0b-6d9d-4f9e-97b4-7b97a8bf0f65,Daniel Doyle,danielle_johnson@amazon.com,58.71.52.174,Brazil,amazon.com,8808,garzaanthony@yahoo.com,Invoice Update is Ready,"Dear User,\n\nWe hope you are doing well.\n\nY...",...,09:42:14,Saturday,February,9,English,Social Media,Desktop,Apple Mail,22,Legitimate
1,19a1bcd0-10fb-468d-9d9f-4be5316a7353,Netflix Security,admin@crypto-airdrop.win,50.35.23.170,Germany,crypto-airdrop.win,301,robinsonwilliam@gmail.com,Critical: Unlock Your Profile,"Good Afternoon,\n\nAn unauthorized login was d...",...,15:52:55,Tuesday,November,15,English,Government,Desktop,Outlook,100,Phishing
2,911508b9-a61d-4068-8862-862ed1acc615,Kimberly Robinson,anthony_gonzalez@amazon.com,168.255.202.227,Singapore,amazon.com,5258,lisa02@gmail.com,Project Statement Today,"Dear Valued Customer,\n\nThis is an automated ...",...,17:17:18,Friday,January,17,English,Shopping,Mobile,Apple Mail,12,Legitimate
3,4c390fa5-1c58-47ff-a646-b6a223481dd1,Apple Security,support@login-confirm.biz,196.91.54.223,Singapore,login-confirm.biz,310,jpeterson@yahoo.com,Warning: Recover Your Subscription,"Dear Client,\n\nSuspicious activity has been d...",...,10:22:35,Saturday,June,10,English,Government,Tablet,Yahoo Mail,98,Phishing
4,81fd1fe8-3c2e-433a-af47-f23f92365d34,James Howard,jgallagher@google.com,64.115.32.87,United States,google.com,6319,cassandra07@yahoo.com,Project Update Available,"Dear Customer,\n\nWe hope you are doing well.\...",...,09:37:45,Friday,November,9,English,Shopping,Desktop,Apple Mail,20,Legitimate

Inital Data Types:
email_id                     object
sender_name                  object
sender_email                 object
sender_ip                    object
sender_country               object
sender_domain                object
domain_age_days               int64
recipient_email              object
subject                      object
email_body                   object
contains_link                object
url_domain                   object
url_reputation               object
contains_attachment          object
attachment_type              object
brand_impersonated           object
spf_status                   object
dkim_status                  object
dmarc_status                 object
is_html_email                object
email_length                  int64
word_count                    int64
reading_time_minutes        float64
character_entropy           float64
readability_score             int64
num_links                     int64
num_special_characters        int64
num_uppercase_words           int64
suspicious_keyword_count      int64
urgency_score                 int64
grammar_score                 int64
sender_reputation            object
spoofed_domain               object
sent_date                    object
sent_time                    object
day_of_week                  object
month                        object
hour                          int64
language                     object
email_category               object
device_type                  object
email_client                 object
phishing_probability          int64
label                        object
dtype: object

Number of Distinct Values per Column:
email_id                    50000
sender_name                 25835
sender_email                29635
sender_ip                   49999
sender_country                 12
sender_domain                  20
domain_age_days              7966
recipient_email             45783
subject                      3352
email_body                  50000
contains_link                   2
url_domain                     20
url_reputation                  3
contains_attachment             2
attachment_type                 6
brand_impersonated             19
spf_status                      2
dkim_status                     2
dmarc_status                    2
is_html_email                   2
email_length                  269
word_count                     44
reading_time_minutes           22
character_entropy              46
readability_score               4
num_links                       6
num_special_characters          6
num_uppercase_words             2
suspicious_keyword_count       23
urgency_score                   9
grammar_score                  56
sender_reputation               3
spoofed_domain                  2
sent_date                    1097
sent_time                   38014
day_of_week                     7
month                          12
hour                           24
language                        1
email_category                 10
device_type                     4
email_client                    5
phishing_probability           92
label                           2
dtype: int64

Second basic dataset properties:
Shape:
(100000, 30)

First 5 Rows:

,raw_text,subject,body_plain,body_html,from_address,from_domain,reply_to,to_addresses,cc_addresses,date,...,has_html,num_urls,num_emails_in_body,num_phone_numbers,contains_tracking_token,x_spam_score,user_agent,list_unsubscribe,language,label
0,"Subject: Release notes v2.6.4\nDear Vik,\n\nWe...",Release notes v2.6.4,"Dear Vik,\n\nWe received invoice 765713. It wi...",NaN,leo.wilson@adatum.net,adatum.net,NaN,kathy_taylor@notifications.net,NaN,2024-09-13T16:25:32,...,False,0,0,1,False,0.00,Microsoft Outlook,NaN,en,0
1,"Subject: WINNER! Claim your reward\nDear user,...",WINNER! Claim your reward,"Dear user,\n\nYour parcel has been flagged. To...",NaN,riya_miller313@proton.me,proton.me,NaN,olivia_wilson841@accounts-mail.com,NaN,2024-07-10T01:15:32,...,False,1,0,1,False,4.82,Mutt,NaN,en,1
2,"Subject: Follow-up: onboarding tasks\nHi Zack,...",Follow-up: onboarding tasks,"Hi Zack,\n\nHere are the notes from our meetin...",NaN,wendytaylor@cohosu.org,cohosu.org,NaN,vikwilliams@contoso.com,NaN,2024-04-23T16:20:32,...,False,0,0,0,False,0.00,Apple Mail,NaN,de,0
3,Subject: Limited-time offer: $119 cloud storag...,Limited-time offer: $119 cloud storage,"Attention Bob,\n\nWe detected unusual activity...",<html><body><h3>Limited-time offer: $119 cloud...,vik.brown@outlook.com,outlook.com,carol.johnson@icloud.com,carol.rodriguez@devops.local,NaN,2024-06-07T19:15:32,...,True,2,0,1,False,9.15,Mutt,NaN,it,1
4,"Subject: Weekly update - Legal\nTeam,\n\nNotes...",Weekly update - Legal,"Team,\n\nNotes from Legal daily standup attach...","<p>Team,<br/><br/>Notes from Legal daily stand...",grace_taylor@globalbank.com,globalbank.com,NaN,leo_wilson@notifications.net,NaN,2024-07-05T11:33:32,...,True,0,0,0,False,0.00,Thunderbird,NaN,it,0

Inital Data Types:
raw_text                    object
subject                     object
body_plain                  object
body_html                   object
from_address                object
from_domain                 object
reply_to                    object
to_addresses                object
cc_addresses                object
date                        object
hour_of_day                  int64
message_id                  object
in_reply_to                 object
num_received_headers         int64
received_origin_ip          object
spf_result                  object
dkim_result                 object
dmarc_result                object
has_attachments               bool
attachment_types            object
has_html                      bool
num_urls                     int64
num_emails_in_body           int64
num_phone_numbers            int64
contains_tracking_token       bool
x_spam_score               float64
user_agent                  object
list_unsubscribe            object
language                    object
label                        int64
dtype: object

Number of Distinct Values per Column:
raw_text                    95109
subject                     16684
body_plain                  80518
body_html                   38514
from_address                42740
from_domain                    18
reply_to                    15374
to_addresses                42591
cc_addresses                19092
date                        99668
hour_of_day                    24
message_id                 100000
in_reply_to                 14973
num_received_headers            6
received_origin_ip         100000
spf_result                      3
dkim_result                     3
dmarc_result                    3
has_attachments                 2
attachment_types            20139
has_html                        2
num_urls                        3
num_emails_in_body              2
num_phone_numbers               3
contains_tracking_token         2
x_spam_score                  802
user_agent                     13
list_unsubscribe            19909
language                        5
label                           2
dtype: int64

In [ ]:
#This code block is used to clean and prepare the datasets for use. It is also used to merge the datasets together to create a third dataset.

In [3]:
#This code block is used to build and train the classifier model using classical ML techniques.

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

vectorizer = TfidfVectorizer()
model = LogisticRegression()